### ISSUE TITLE
Update to null safety?

### ISSUE THREAD

**Issue by TolgaYld** [AndreeWille/time-span#1]
question is the heading.

thx :)

**Comment by AndreeWille** [comment]
Hi! 

what exactly would you like to have changed?

**Comment by TolgaYld** [comment]
> Hi!
> 
> what exactly would you like to have changed?

do u can update ur package to a null safety version? :)

**Comment by TolgaYld** [comment]
aso du verstehst glaub ich deutsch :D ... das paket unterstützt nicht die null safety version von flutter... deswegen frag ich :)

**Comment by AndreeWille** [comment]
was genau muss denn geändert werden um null safety in flutter zu unterstützen? Ich kenne Flutter nicht wirklich gut.
(what exactly has to be changed to support zero safety in flutter? I don't really know Flutter very well. )

**Comment by TolgaYld** [comment]
> was genau muss denn geändert werden um null safety in flutter zu unterstützen? Ich kenne Flutter nicht wirklich gut.
> (what exactly has to be changed to support zero safety in flutter? I don't really know Flutter very well. )

https://www.youtube.com/watch?v=bvq7wbn4VAA

hier ist ein link von der offiziellen Seite, wie das umgesetzt wird. total einfach. Wenn du trotzdem noch fragen hast, schieß los, helfe gerne so gut es geht.
(Look at this)

Danke für dei raschen antworten!

**Comment by AndreeWille** [comment]
Ich habe den code migriert. 
Siehe bc0a3b4efc1f33305cd50258d25e2579536e0cce

Soweit ist das Issue für mich erledigt. Falls es Probleme mit dem Update geben sollte, dann eröffne gerne ein neues Issue.
